package tokens

import "github.com/zodimo/go-compose/compose/ui/unit"

var FilledTextFieldTokens = FilledTextFieldTokensData{
	ActiveIndicatorColor:           ColorSchemeKeyTokens.OnSurfaceVariant,
	ActiveIndicatorHeight:          unit.Dp(1.0),
	CaretColor:                     ColorSchemeKeyTokens.Primary,
	ContainerColor:                 ColorSchemeKeyTokens.SurfaceContainerHighest,
	ContainerShape:                 ShapeKeyTokens.CornerExtraSmallTop,
	DisabledActiveIndicatorColor:   ColorSchemeKeyTokens.OnSurface,
	DisabledActiveIndicatorHeight:  unit.Dp(1.0),
	DisabledActiveIndicatorOpacity: 0.38,
	DisabledContainerColor:         ColorSchemeKeyTokens.OnSurface,
	DisabledContainerOpacity:       0.04,
	DisabledInputColor:             ColorSchemeKeyTokens.OnSurface,
	DisabledInputOpacity:           0.38,
	DisabledLabelColor:             ColorSchemeKeyTokens.OnSurface,
	DisabledLabelOpacity:           0.38,
	DisabledLeadingIconColor:       ColorSchemeKeyTokens.OnSurface,
	DisabledLeadingIconOpacity:     0.38,
	DisabledSupportingColor:        ColorSchemeKeyTokens.OnSurface,
	DisabledSupportingOpacity:      0.38,
	DisabledTrailingIconColor:      ColorSchemeKeyTokens.OnSurface,
	DisabledTrailingIconOpacity:    0.38,
	ErrorActiveIndicatorColor:      ColorSchemeKeyTokens.Error,
	ErrorFocusActiveIndicatorColor: ColorSchemeKeyTokens.Error,
	ErrorFocusCaretColor:           ColorSchemeKeyTokens.Error,
	ErrorFocusInputColor:           ColorSchemeKeyTokens.OnSurface,
	ErrorFocusLabelColor:           ColorSchemeKeyTokens.Error,
	ErrorFocusLeadingIconColor:     ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorFocusSupportingColor:      ColorSchemeKeyTokens.Error,
	ErrorFocusTrailingIconColor:    ColorSchemeKeyTokens.Error,
	ErrorHoverActiveIndicatorColor: ColorSchemeKeyTokens.OnErrorContainer,
	ErrorHoverInputColor:           ColorSchemeKeyTokens.OnSurface,
	ErrorHoverLabelColor:           ColorSchemeKeyTokens.OnErrorContainer,
	ErrorHoverLeadingIconColor:     ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorHoverSupportingColor:      ColorSchemeKeyTokens.Error,
	ErrorHoverTrailingIconColor:    ColorSchemeKeyTokens.OnErrorContainer,
	ErrorInputColor:                ColorSchemeKeyTokens.OnSurface,
	ErrorLabelColor:                ColorSchemeKeyTokens.Error,
	ErrorLeadingIconColor:          ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorSupportingColor:           ColorSchemeKeyTokens.Error,
	ErrorTrailingIconColor:         ColorSchemeKeyTokens.Error,
	FocusActiveIndicatorColor:      ColorSchemeKeyTokens.Primary,
	FocusActiveIndicatorHeight:     unit.Dp(2.0),
	FocusInputColor:                ColorSchemeKeyTokens.OnSurface,
	FocusLabelColor:                ColorSchemeKeyTokens.Primary,
	FocusLeadingIconColor:          ColorSchemeKeyTokens.OnSurfaceVariant,
	FocusSupportingColor:           ColorSchemeKeyTokens.OnSurfaceVariant,
	FocusTrailingIconColor:         ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverActiveIndicatorColor:      ColorSchemeKeyTokens.OnSurface,
	HoverActiveIndicatorHeight:     unit.Dp(1.0),
	HoverInputColor:                ColorSchemeKeyTokens.OnSurface,
	HoverLabelColor:                ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverLeadingIconColor:          ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverSupportingColor:           ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverTrailingIconColor:         ColorSchemeKeyTokens.OnSurfaceVariant,
	InputColor:                     ColorSchemeKeyTokens.OnSurface,
	InputFont:                      TypographyKeyTokens.BodyLarge,
	InputPlaceholderColor:          ColorSchemeKeyTokens.OnSurfaceVariant,
	InputPrefixColor:               ColorSchemeKeyTokens.OnSurfaceVariant,
	InputSuffixColor:               ColorSchemeKeyTokens.OnSurfaceVariant,
	LabelColor:                     ColorSchemeKeyTokens.OnSurfaceVariant,
	LabelFont:                      TypographyKeyTokens.BodyLarge,
	LeadingIconColor:               ColorSchemeKeyTokens.OnSurfaceVariant,
	LeadingIconSize:                unit.Dp(24.0),
	SupportingColor:                ColorSchemeKeyTokens.OnSurfaceVariant,
	SupportingFont:                 TypographyKeyTokens.BodySmall,
	TrailingIconColor:              ColorSchemeKeyTokens.OnSurfaceVariant,
	TrailingIconSize:               unit.Dp(24.0),
}

type FilledTextFieldTokensData struct {
	ActiveIndicatorColor           ColorSchemeTokenKey
	ActiveIndicatorHeight          unit.Dp
	CaretColor                     ColorSchemeTokenKey
	ContainerColor                 ColorSchemeTokenKey
	ContainerShape                 ShapeTokenKey
	DisabledActiveIndicatorColor   ColorSchemeTokenKey
	DisabledActiveIndicatorHeight  unit.Dp
	DisabledActiveIndicatorOpacity float32
	DisabledContainerColor         ColorSchemeTokenKey
	DisabledContainerOpacity       float32
	DisabledInputColor             ColorSchemeTokenKey
	DisabledInputOpacity           float32
	DisabledLabelColor             ColorSchemeTokenKey
	DisabledLabelOpacity           float32
	DisabledLeadingIconColor       ColorSchemeTokenKey
	DisabledLeadingIconOpacity     float32
	DisabledSupportingColor        ColorSchemeTokenKey
	DisabledSupportingOpacity      float32
	DisabledTrailingIconColor      ColorSchemeTokenKey
	DisabledTrailingIconOpacity    float32
	ErrorActiveIndicatorColor      ColorSchemeTokenKey
	ErrorFocusActiveIndicatorColor ColorSchemeTokenKey
	ErrorFocusCaretColor           ColorSchemeTokenKey
	ErrorFocusInputColor           ColorSchemeTokenKey
	ErrorFocusLabelColor           ColorSchemeTokenKey
	ErrorFocusLeadingIconColor     ColorSchemeTokenKey
	ErrorFocusSupportingColor      ColorSchemeTokenKey
	ErrorFocusTrailingIconColor    ColorSchemeTokenKey
	ErrorHoverActiveIndicatorColor ColorSchemeTokenKey
	ErrorHoverInputColor           ColorSchemeTokenKey
	ErrorHoverLabelColor           ColorSchemeTokenKey
	ErrorHoverLeadingIconColor     ColorSchemeTokenKey
	ErrorHoverSupportingColor      ColorSchemeTokenKey
	ErrorHoverTrailingIconColor    ColorSchemeTokenKey
	ErrorInputColor                ColorSchemeTokenKey
	ErrorLabelColor                ColorSchemeTokenKey
	ErrorLeadingIconColor          ColorSchemeTokenKey
	ErrorSupportingColor           ColorSchemeTokenKey
	ErrorTrailingIconColor         ColorSchemeTokenKey
	FocusActiveIndicatorColor      ColorSchemeTokenKey
	FocusActiveIndicatorHeight     unit.Dp
	FocusInputColor                ColorSchemeTokenKey
	FocusLabelColor                ColorSchemeTokenKey
	FocusLeadingIconColor          ColorSchemeTokenKey
	FocusSupportingColor           ColorSchemeTokenKey
	FocusTrailingIconColor         ColorSchemeTokenKey
	HoverActiveIndicatorColor      ColorSchemeTokenKey
	HoverActiveIndicatorHeight     unit.Dp
	HoverInputColor                ColorSchemeTokenKey
	HoverLabelColor                ColorSchemeTokenKey
	HoverLeadingIconColor          ColorSchemeTokenKey
	HoverSupportingColor           ColorSchemeTokenKey
	HoverTrailingIconColor         ColorSchemeTokenKey
	InputColor                     ColorSchemeTokenKey
	InputFont                      TypographyTokenKey
	InputPlaceholderColor          ColorSchemeTokenKey
	InputPrefixColor               ColorSchemeTokenKey
	InputSuffixColor               ColorSchemeTokenKey
	LabelColor                     ColorSchemeTokenKey
	LabelFont                      TypographyTokenKey
	LeadingIconColor               ColorSchemeTokenKey
	LeadingIconSize                unit.Dp
	SupportingColor                ColorSchemeTokenKey
	SupportingFont                 TypographyTokenKey
	TrailingIconColor              ColorSchemeTokenKey
	TrailingIconSize               unit.Dp
}
