package tokens

import (
	"github.com/zodimo/go-compose/compose/ui/unit"
)

var OutlineFilledTextFieldTokens = OutlinedTextFieldTokensData{
	CaretColor:                  ColorSchemeKeyTokens.Primary,
	ContainerHeight:             unit.Dp(56),
	ContainerShape:              ShapeKeyTokens.CornerExtraSmall,
	DisabledInputColor:          ColorSchemeKeyTokens.OnSurface,
	DisabledInputOpacity:        0.38,
	DisabledLabelColor:          ColorSchemeKeyTokens.OnSurface,
	DisabledLabelOpacity:        0.38,
	DisabledLeadingIconColor:    ColorSchemeKeyTokens.OnSurface,
	DisabledLeadingIconOpacity:  0.38,
	DisabledOutlineColor:        ColorSchemeKeyTokens.OnSurface,
	DisabledOutlineOpacity:      0.12,
	DisabledOutlineWidth:        unit.Dp(1),
	DisabledSupportingColor:     ColorSchemeKeyTokens.OnSurface,
	DisabledSupportingOpacity:   0.38,
	DisabledTrailingIconColor:   ColorSchemeKeyTokens.OnSurface,
	DisabledTrailingIconOpacity: 0.38,
	ErrorFocusCaretColor:        ColorSchemeKeyTokens.Error,
	ErrorFocusInputColor:        ColorSchemeKeyTokens.OnSurface,
	ErrorFocusLabelColor:        ColorSchemeKeyTokens.Error,
	ErrorFocusLeadingIconColor:  ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorFocusOutlineColor:      ColorSchemeKeyTokens.Error,
	ErrorFocusSupportingColor:   ColorSchemeKeyTokens.Error,
	ErrorFocusTrailingIconColor: ColorSchemeKeyTokens.Error,
	ErrorHoverInputColor:        ColorSchemeKeyTokens.OnSurface,
	ErrorHoverLabelColor:        ColorSchemeKeyTokens.OnErrorContainer,
	ErrorHoverLeadingIconColor:  ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorHoverOutlineColor:      ColorSchemeKeyTokens.OnErrorContainer,
	ErrorHoverSupportingColor:   ColorSchemeKeyTokens.Error,
	ErrorHoverTrailingIconColor: ColorSchemeKeyTokens.OnErrorContainer,
	ErrorInputColor:             ColorSchemeKeyTokens.OnSurface,
	ErrorLabelColor:             ColorSchemeKeyTokens.Error,
	ErrorLeadingIconColor:       ColorSchemeKeyTokens.OnSurfaceVariant,
	ErrorOutlineColor:           ColorSchemeKeyTokens.Error,
	ErrorSupportingColor:        ColorSchemeKeyTokens.Error,
	ErrorTrailingIconColor:      ColorSchemeKeyTokens.Error,
	FocusInputColor:             ColorSchemeKeyTokens.OnSurface,
	FocusLabelColor:             ColorSchemeKeyTokens.Primary,
	FocusLeadingIconColor:       ColorSchemeKeyTokens.OnSurfaceVariant,
	FocusOutlineColor:           ColorSchemeKeyTokens.Primary,
	FocusOutlineWidth:           unit.Dp(2),
	FocusSupportingColor:        ColorSchemeKeyTokens.OnSurfaceVariant,
	FocusTrailingIconColor:      ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverInputColor:             ColorSchemeKeyTokens.OnSurface,
	HoverLabelColor:             ColorSchemeKeyTokens.OnSurface,
	HoverLeadingIconColor:       ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverOutlineColor:           ColorSchemeKeyTokens.OnSurface,
	HoverOutlineWidth:           unit.Dp(1),
	HoverSupportingColor:        ColorSchemeKeyTokens.OnSurfaceVariant,
	HoverTrailingIconColor:      ColorSchemeKeyTokens.OnSurfaceVariant,
	InputColor:                  ColorSchemeKeyTokens.OnSurface,
	InputFont:                   TypographyKeyTokens.BodyLarge,
	InputPlaceholderColor:       ColorSchemeKeyTokens.OnSurfaceVariant,
	InputPrefixColor:            ColorSchemeKeyTokens.OnSurfaceVariant,
	InputSuffixColor:            ColorSchemeKeyTokens.OnSurfaceVariant,
	LabelColor:                  ColorSchemeKeyTokens.OnSurfaceVariant,
	LabelFont:                   TypographyKeyTokens.BodyLarge,
	LeadingIconColor:            ColorSchemeKeyTokens.OnSurfaceVariant,
	LeadingIconSize:             unit.Dp(24),
	OutlineColor:                ColorSchemeKeyTokens.Outline,
	OutlineWidth:                unit.Dp(1),
	SupportingColor:             ColorSchemeKeyTokens.OnSurfaceVariant,
	SupportingFont:              TypographyKeyTokens.BodySmall,
	TrailingIconColor:           ColorSchemeKeyTokens.OnSurfaceVariant,
	TrailingIconSize:            unit.Dp(24),
}

type OutlinedTextFieldTokensData struct {
	CaretColor                  ColorSchemeTokenKey
	ContainerHeight             unit.Dp
	ContainerShape              ShapeTokenKey
	DisabledInputColor          ColorSchemeTokenKey
	DisabledInputOpacity        float32
	DisabledLabelColor          ColorSchemeTokenKey
	DisabledLabelOpacity        float32
	DisabledLeadingIconColor    ColorSchemeTokenKey
	DisabledLeadingIconOpacity  float32
	DisabledOutlineColor        ColorSchemeTokenKey
	DisabledOutlineOpacity      float32
	DisabledOutlineWidth        unit.Dp
	DisabledSupportingColor     ColorSchemeTokenKey
	DisabledSupportingOpacity   float32
	DisabledTrailingIconColor   ColorSchemeTokenKey
	DisabledTrailingIconOpacity float32

	ErrorFocusCaretColor        ColorSchemeTokenKey
	ErrorFocusInputColor        ColorSchemeTokenKey
	ErrorFocusLabelColor        ColorSchemeTokenKey
	ErrorFocusLeadingIconColor  ColorSchemeTokenKey
	ErrorFocusOutlineColor      ColorSchemeTokenKey
	ErrorFocusSupportingColor   ColorSchemeTokenKey
	ErrorFocusTrailingIconColor ColorSchemeTokenKey
	ErrorHoverInputColor        ColorSchemeTokenKey
	ErrorHoverLabelColor        ColorSchemeTokenKey
	ErrorHoverLeadingIconColor  ColorSchemeTokenKey
	ErrorHoverOutlineColor      ColorSchemeTokenKey
	ErrorHoverSupportingColor   ColorSchemeTokenKey
	ErrorHoverTrailingIconColor ColorSchemeTokenKey
	ErrorInputColor             ColorSchemeTokenKey
	ErrorLabelColor             ColorSchemeTokenKey
	ErrorLeadingIconColor       ColorSchemeTokenKey
	ErrorOutlineColor           ColorSchemeTokenKey
	ErrorSupportingColor        ColorSchemeTokenKey
	ErrorTrailingIconColor      ColorSchemeTokenKey
	FocusInputColor             ColorSchemeTokenKey
	FocusLabelColor             ColorSchemeTokenKey
	FocusLeadingIconColor       ColorSchemeTokenKey
	FocusOutlineColor           ColorSchemeTokenKey
	FocusOutlineWidth           unit.Dp
	FocusSupportingColor        ColorSchemeTokenKey
	FocusTrailingIconColor      ColorSchemeTokenKey
	HoverInputColor             ColorSchemeTokenKey
	HoverLabelColor             ColorSchemeTokenKey
	HoverLeadingIconColor       ColorSchemeTokenKey
	HoverOutlineColor           ColorSchemeTokenKey
	HoverOutlineWidth           unit.Dp
	HoverSupportingColor        ColorSchemeTokenKey
	HoverTrailingIconColor      ColorSchemeTokenKey
	InputColor                  ColorSchemeTokenKey
	InputFont                   TypographyTokenKey
	InputPlaceholderColor       ColorSchemeTokenKey
	InputPrefixColor            ColorSchemeTokenKey
	InputSuffixColor            ColorSchemeTokenKey
	LabelColor                  ColorSchemeTokenKey
	LabelFont                   TypographyTokenKey
	LeadingIconColor            ColorSchemeTokenKey
	LeadingIconSize             unit.Dp
	OutlineColor                ColorSchemeTokenKey
	OutlineWidth                unit.Dp
	SupportingColor             ColorSchemeTokenKey
	SupportingFont              TypographyTokenKey
	TrailingIconColor           ColorSchemeTokenKey
	TrailingIconSize            unit.Dp
}
